[package]
name = "phi512"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "phi512"
crate-type = ["cdylib", "rlib"]

[dependencies]
iced-x86 = { workspace = true }
libc = { workspace = true }
avx512-xlate = { path = "../avx512-xlate" }
phi-vpu = { path = "../phi-vpu" }
