[package]
name = "phi-stream"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "phi-stream"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["env"] }
crossterm = "0.28"
libc = { workspace = true }

[build-dependencies]
bindgen = "0.72"
