//! `avx512-xlate`: turn a function written in AVX-512 into one the card can
//! run.
//!
//! The observation this tool is built on: Knights Corner is x86-64. The
//! scalar half of an AVX-512 function, the pointer arithmetic, the loop
//! counter, the branches, is already valid card code and needs no
//! translation at all. Only the EVEX instructions have to be rewritten.
//!
//! So the pipeline is: assemble the AVX-512 source with the host's own
//! assembler, which can encode instructions this host cannot execute;
//! decode the result; rewrite each EVEX instruction into its MVEX
//! equivalent; pass everything else through after checking it against the
//! deletions Knights Corner made to the base instruction set; and emit
//! assembly for the card.
//!
//! Instruction lengths change during the rewrite, since an unaligned
//! AVX-512 load becomes two card instructions. Relative branch
//! displacements would therefore be wrong if bytes were copied verbatim,
//! so branch targets are collected first, a label is emitted at each one,
//! and branches are emitted as text against those labels for the card's
//! assembler to resolve.

use std::collections::BTreeSet;
use std::io::Write;
use std::process::Command;

use anyhow::{bail, Context, Result};
use iced_x86::{Decoder, DecoderOptions, Formatter, Instruction, IntelFormatter, Mnemonic, OpKind};

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("usage: avx512-xlate <input.s> [--name FN] [--out OUT.S]");
        eprintln!();
        eprintln!("Assembles an AVX-512 function with llvm-mc, translates every EVEX");
        eprintln!("instruction to Knights Corner MVEX, and writes card assembly.");
        std::process::exit(2);
    }
    let input = &args[1];
    let mut name = "kernel".to_string();
    let mut out: Option<String> = None;
    let mut i = 2;
    while i < args.len() {
        match args[i].as_str() {
            "--name" => {
                name = args.get(i + 1).context("--name needs a value")?.clone();
                i += 2;
            }
            "--out" => {
                out = Some(args.get(i + 1).context("--out needs a value")?.clone());
                i += 2;
            }
            other => bail!("unknown argument {other}"),
        }
    }

    let code = assemble(input)?;
    let text = translate_function(&code, &name)?;
    match out {
        Some(p) => {
            std::fs::write(&p, text).with_context(|| format!("writing {p}"))?;
            eprintln!("wrote {p}");
        }
        None => std::io::stdout().write_all(text.as_bytes())?,
    }
    Ok(())
}

/// Assemble the AVX-512 source with `llvm-mc` and return the `.text` bytes.
///
/// The host assembler encodes AVX-512 happily; it is the host *processor*
/// that cannot run it. That gap is the whole reason this tool exists.
fn assemble(path: &str) -> Result<Vec<u8>> {
    let obj = std::env::temp_dir().join(format!("avx512-xlate-{}.o", std::process::id()));
    let status = Command::new("llvm-mc")
        .args(["-triple=x86_64", "-mattr=+avx512f", "-filetype=obj", "-o"])
        .arg(&obj)
        .arg(path)
        .status()
        .context("running llvm-mc; is it on PATH?")?;
    if !status.success() {
        bail!("llvm-mc failed to assemble {path}");
    }
    let data = std::fs::read(&obj)?;
    let _ = std::fs::remove_file(&obj);
    section_text(&data).context("no .text section in the assembled object")
}

/// Pull the code section out of the assembled relocatable.
fn section_text(data: &[u8]) -> Option<Vec<u8>> {
    use object::{Object, ObjectSection};
    let file = object::File::parse(data).ok()?;
    let text = file.section_by_name(".text")?;
    Some(text.data().ok()?.to_vec())
}

/// Decode, translate, and emit card assembly for one function body.
fn translate_function(code: &[u8], name: &str) -> Result<String> {
    // Pass one: decode everything, and note every address a branch can
    // reach, so a label can be planted there.
    let mut insns: Vec<Instruction> = Vec::new();
    let mut decoder = Decoder::with_ip(64, code, 0, DecoderOptions::NONE);
    while decoder.can_decode() {
        insns.push(decoder.decode());
    }
    let mut targets: BTreeSet<u64> = BTreeSet::new();
    for insn in &insns {
        if is_branch(insn) {
            if let Some(t) = branch_target(insn) {
                targets.insert(t);
            }
        }
    }

    let mut fmt = IntelFormatter::new();
    fmt.options_mut().set_space_after_operand_separator(true);
    // GNU as in .intel_syntax mode wants 0x40, not the MASM 40h that iced
    // emits by default.
    fmt.options_mut().set_hex_prefix("0x");
    fmt.options_mut().set_hex_suffix("");
    fmt.options_mut().set_uppercase_hex(false);
    let mut s = String::new();
    let mut translated_count = 0usize;
    let mut passthrough_count = 0usize;

    s.push_str(&format!("// {name}: generated by avx512-xlate from AVX-512 source.\n"));
    s.push_str("// Do not edit. EVEX instructions have been rewritten as MVEX; the\n");
    s.push_str("// scalar instructions are the originals, which Knights Corner runs as\n");
    s.push_str("// they are because it is an x86-64 core.\n");
    s.push_str(".intel_syntax noprefix\n.text\n");
    s.push_str(&format!(".globl {name}\n.type {name}, @function\n{name}:\n"));

    for insn in &insns {
        if targets.contains(&insn.ip()) {
            s.push_str(&format!(".L_{:x}:\n", insn.ip()));
        }
        let mut text = String::new();
        fmt.format(insn, &mut text);

        if is_evex(insn) {
            let translated = avx512_xlate::translate(insn).map_err(|e| anyhow::anyhow!("{e}"))?;
            s.push_str(&format!("    // {text}\n"));
            for t in &translated {
                s.push_str(&format!("    .byte {}  // {}\n", hex(&t.bytes), t.text));
            }
            translated_count += 1;
        } else if is_branch(insn) {
            let target = branch_target(insn).context("branch with no computable target")?;
            let mnem = text.split_whitespace().next().unwrap_or("jmp").to_string();
            s.push_str(&format!("    {mnem} .L_{target:x}\n"));
            passthrough_count += 1;
        } else {
            if let Some(reason) = knc_illegal(insn) {
                bail!("{text}: {reason}");
            }
            s.push_str(&format!("    {text}\n"));
            passthrough_count += 1;
        }
    }
    s.push_str(&format!(".size {name}, .-{name}\n"));
    eprintln!("{name}: {translated_count} EVEX instructions translated, {passthrough_count} scalar passed through");
    Ok(s)
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("0x{b:02x}")).collect::<Vec<_>>().join(", ")
}

/// An EVEX-encoded instruction is one this host can assemble but not run,
/// and the one this tool has to rewrite. iced reports the encoding
/// directly.
fn is_evex(insn: &Instruction) -> bool {
    insn.encoding() == iced_x86::EncodingKind::EVEX
}

fn is_branch(insn: &Instruction) -> bool {
    matches!(insn.op0_kind(), OpKind::NearBranch16 | OpKind::NearBranch32 | OpKind::NearBranch64)
}

fn branch_target(insn: &Instruction) -> Option<u64> {
    match insn.op0_kind() {
        OpKind::NearBranch64 => Some(insn.near_branch64()),
        OpKind::NearBranch32 => Some(insn.near_branch32().into()),
        OpKind::NearBranch16 => Some(insn.near_branch16().into()),
        _ => None,
    }
}

/// The base-instruction-set deletions that matter for generated code.
/// `docs/research/isa-deletions.md` has the full list and its sources; the
/// ones a compiler or a hand-written kernel actually emits are these.
fn knc_illegal(insn: &Instruction) -> Option<&'static str> {
    match insn.mnemonic() {
        Mnemonic::Cmovo
        | Mnemonic::Cmovno
        | Mnemonic::Cmovb
        | Mnemonic::Cmovae
        | Mnemonic::Cmove
        | Mnemonic::Cmovne
        | Mnemonic::Cmovbe
        | Mnemonic::Cmova
        | Mnemonic::Cmovs
        | Mnemonic::Cmovns
        | Mnemonic::Cmovp
        | Mnemonic::Cmovnp
        | Mnemonic::Cmovl
        | Mnemonic::Cmovge
        | Mnemonic::Cmovle
        | Mnemonic::Cmovg => Some("cmov is not supported in 64-bit mode on Knights Corner (ISA reference B.2)"),
        Mnemonic::Pause => Some("pause is not supported; the card has DELAY instead (ISA reference B.2)"),
        Mnemonic::Lfence | Mnemonic::Mfence | Mnemonic::Sfence => Some("the fence instructions are absent; use lock addq 0, [rsp]"),
        Mnemonic::Prefetcht0 | Mnemonic::Prefetcht1 | Mnemonic::Prefetcht2 | Mnemonic::Prefetchnta | Mnemonic::Prefetchw => {
            Some("scalar prefetch is absent; the card has VPREFETCH* (SSDG 4.2.12)")
        }
        Mnemonic::Popcnt | Mnemonic::Lzcnt | Mnemonic::Tzcnt => Some("not present on the card in scalar form"),
        Mnemonic::Clflush => Some("clflush is absent; the card has CLEVICT0/1"),
        _ => {
            if insn.encoding() == iced_x86::EncodingKind::VEX {
                Some("VEX-encoded AVX: the card has no xmm or ymm registers at all (ISA reference B.2)")
            } else {
                None
            }
        }
    }
}
